[workspace]
members = ["pbjson", "pbjson-build", "pbjson-test", "pbjson-types"]

exclude = ["pbjson-no-std"]
resolver = "2"

[patch.'https://github.com/permissionlessweb/pbjson']
informalsystems-pbjson = { path = "pbjson" }
informalsystems-pbjson-build = { path = "pbjson-build" }
informalsystems-pbjson-types = { path = "pbjson-types" }
