[package]
name = "informalsystems-pbjson-test"
version = "0.7.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"
description = "Test resources for pbjson converion"
repository = "https://github.com/informalsystems/pbjson"
publish = false

[lib]
name = "pbjson_test"

[features]
default = ["std"]
std = [
    "prost/std",
    "serde/std",
    "informalsystems-pbjson/std",
    "informalsystems-pbjson-types/std",
]
ignore-unknown-fields = []
btree = []
emit-fields = []
use-integers-for-enums = []
preserve-proto-field-names = []

[dependencies]
informalsystems-pbjson = { git = "https://github.com/permissionlessweb/pbjson", branch = "zk-mvp" }
informalsystems-pbjson-types = { git = "https://github.com/permissionlessweb/pbjson", branch = "zk-mvp" }
prost = { version = "0.14.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[build-dependencies]
informalsystems-pbjson-build = { git = "https://github.com/permissionlessweb/pbjson", branch = "zk-mvp" }
prost-build = "0.14.1"

[dev-dependencies]
chrono = "0.4"
serde_json = "1.0"
